### ISSUE TITLE
[Task list] Melhorias

### ISSUE THREAD

**Issue by lostdusty** [AlternativeOn/pgo#1]
- [X] Adicionar timeouts para as requests
- [X] Reutilizar o mesmo client http
- [X] Mover as urls para uma constante
- [X] Verificar erros nos json.*
- [X] Retornar uma struct em pgo.GetUserInfo
